languageCode = 'en-us'
title = "Upbeat Tales"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Comment out to disable taxonomies in Docsy
disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "G-FV8MKRQ6HS"

# Language configuration

[languages]
[languages.en]
title = "Upbeat Tales"
description = "Fun short stories from all across the English-speaking world!"
languageName ="English"

# Weight used for sorting.
weight = 1

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
style = "paraiso-dark"
# Uncomment if you want your chosen highlight style used for code blocks without a specified language
# guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
# [outputs]
# section = ["HTML", "print", "RSS"]

[params]
# First one is picked as the Twitter card image if not set on page.
images = ["images/featured-image.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://upbeattales.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/UpbeatTales/site"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
# github_project_repo = "https://github.com/UpbeatTales"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = "site"

# Uncomment this if you have a newer GitHub repo with "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch= "main"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = false
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/UpbeatTales/site/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/UpbeatTales/site/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
[[params.links.apple]]
name = "Apple Podcasts"
url = "https://podcasts.apple.com/us/podcast/upbeat-tales/id1693733174"
icon = "fab fa-apple"
desc = "Listen on Apple Podcasts!"
[[params.links.audible]]
name = "Audible"
url = "https://www.audible.com/pd/ITEM_NAME-Podcast/B0C8RX19RM"
icon = "fab fa-audible"
desc = "Listen on Audible!"
[[params.links.amazon]]
name = "Amazon Music"
url = "https://music.amazon.com/podcasts/4ded59d4-cdd8-40d8-b8e5-378374b8cd1a/upbeat-tales"
icon = "fab fa-amazon"
desc = "Listen on Spotify!"
[[params.links.google]]
name = "Google Podcasts"
url = "https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy9lM2VjN2MxYy9wb2RjYXN0L3Jzcw"
icon = "fab fa-google"
desc = "Listen on Google Podcasts!"
[[params.links.spotify]]
name = "Spotify"
url = "https://open.spotify.com/show/4TJtCRn0R2lWRKHo3Fd0WB?si=f883fb44b5f849f4"
icon = "fab fa-spotify"
desc = "Listen on Spotify!"


[params.markmap]
enable = true
